### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by pj00** [CCOMIT/CareerSpecialtyMentorRequest#2]
#### General
- [x] Wire up authentication
- [ ] Deletes
- [ ] Logging
- [ ] Error page needed, e.g., if you log in as someone with no roles you get blank page w/ no explanation

#### Security
- [ ] Non-student logon needs to redirect to Admin area
- [ ] AppUser.Active == false has no effect

#### Request a Mentor
- [x] Filter dropdowns based on ~~available~~ active mentors
- [x] Filter mentors based on selections
- [x] Handle *request this mentor* click
- [x] Wire submit button
- [ ] Generate emails
- [x] Need resident and fellow training location options
- [x] Include city/state/country in location dropdowns.
- [ ] After clearing all locations that **eduran** is linked to, the med school shows on the mentor list with the icon but no text.

#### Requests
- [ ] Main page needs filter buttons
- [x] Wire up row clicks to edit
- [ ] Are changes to assigned mentors allowed?  Under what circumstances?
- [ ] Set max height for mentor list
- [ ] Show gender, race, etc, in mentor list
- [ ] Illuminate items in mentor list that match user criteria
- [ ] Handle release from mentor and cancellation (are they different?)
- [ ] Mentor name doesn't show in Special Requests column in main table

#### Mentors
- [ ] Revise columns to be displayed on main page
- [x] Keeps losing training locations?
- [x] Wire up row clicks to edit
- [ ] *Current Students* column
- [ ] Improve APR matching, i.e., consider city/state/country/etc
- [x] Add city/state/zip to location dropdowns
- [x] Make sure HawkId doesn't already exist in list when adding
- [ ] If APR is clicked while editing, highlight fields that changed
- [x] When training location duplicates are shown due to duplication in APR data, show "as fellow", "as resident", etc, in dropdown.
- [ ] APR button doesn't recalculate width after pull
- [x] Modal submit handler fires twice.  Might only be true for edit.
- [x] sRavindranath has Bangalore as both med school and train loc, but each got added as separate location record.
- [ ] After manual training location selection, make sure there is an extra blank location provided
- [ ] How to handle success; clear everything but success alert?
- [x] Delete locations that **eduran** is linked to, then reload from apr.  Matching process is hinkey.

#### Locations
- [x] Wire up row clicks to edit
- [x] Need column for college
- [ ] Spruce up Mentors section of modal

#### Users
- [x] New roles
- [x] Specialty selection
- [x] Checkbox for *notify when undecided request received* (but with better text)
- [x] Shows JSON on save

#### Scoring
- [ ] Does scoring algorithm take requested mentor into account?  Maybe it shouldn't, but should somehow illuminate requested mentor in list?
- [ ] Give points to MedSchool if it matches one of the training locations, and vice versa
- [ ] Consider City/State/Country
- [ ] Give point(s) for school match even if college doesn't match

#### Future
- [ ] *Mentor locations* page needed so roles can be assigned to mentor locations

**Comment by pj00** [comment]
Closed to #3
