### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by pj00** [CCOMIT/CareerSpecialtyMentorRequest#3]
#### General
- [ ] Deletes
- [ ] Logging
- [ ] Error page needed, e.g., if you log in as someone with no roles you get blank page w/ no explanation
- [ ] Notifications/Dispatch

#### Security
- [ ] Non-student logon needs to redirect to Admin area
- [ ] AppUser.Active == false has no effect

#### Request a Mentor
- [ ] After clearing all locations that **eduran** is linked to, the med school shows on the mentor list with the icon but no text.

#### Requests
- [ ] Main page needs filter buttons
- [ ] Set max height for mentor list
- [x] Show gender, race, etc, in mentor list
- [ ] Illuminate items in mentor list that match user criteria
- [x] Mentor name doesn't show in Special Requests column in main table

#### Mentors
- [ ] Revise columns to be displayed on main page
- [ ] *Current Students* column
- [ ] Improve APR matching, i.e., consider city/state/country/etc
- [ ] If APR is clicked while editing, highlight fields that changed
- [ ] APR button doesn't recalculate width after pull
- [ ] After manual training location selection, make sure there is an extra blank location provided
- [ ] How to handle success; clear everything but success alert?
- [ ] Make read only, when appropriate

#### Locations
- [ ] Spruce up Mentors section of modal
- [ ] Make read only, when appropriate

#### Scoring
- [ ] Does scoring algorithm take requested mentor into account?  Maybe it shouldn't, but should somehow illuminate requested mentor in list?
- [ ] Give points to MedSchool if it matches one of the training locations, and vice versa
- [ ] Consider City/State/Country
- [ ] Give point(s) for school match even if college doesn't match

#### Future
- [ ] *Mentor locations* page needed so roles can be assigned to mentor locations

#### Questions
- [ ] Are changes to assigned mentors allowed?  Under what circumstances?
- [ ] Handle release from mentor and cancellation (are they different?)

**Comment by pj00** [comment]
closed to #4
