### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by pj00** [CCOMIT/CareerSpecialtyMentorRequest#4]
# Now

#### General
- [x] Deletes
- [x] Logging
- [x] DataTables errors after adding/updating
- [x] Filter views based on AppUser specialty
- [ ] Filter mentor modal based on AppUser specialty

#### Security
- [x] Non-student logon needs to redirect to Admin area
- [ ] AppUser.Active == false has no effect

#### Mentors
- [x] Revise columns to be displayed on main page
- [x] *Current Students* column
- [x] Make read only, when appropriate
- [ ] Can we get Gender/Race/Ethnicity from HR?

#### Locations
- [x] Make read only, when appropriate

# Sooner

#### General
- [ ] Error page needed, e.g., if you log in as someone with no roles you get blank page w/ no explanation
- [ ] Notifications/Dispatch
  * Include notification to (matchmaker?) when all slots are filled
- [ ] Impersonation
- [ ] Is each DataTable search searching everything it needs to?

### Requests
- [ ] Main page needs filter buttons
- [x] Set max height for mentor list
- [x] Make Delete button only available to Admins
- [ ] Add Cancel and Release buttons, both with confirmation dialogs
- [ ] Degree shows as "Unknown" on main page
- [ ] Refine the logic for when the new modal buttons are used/enabled/etc
- [ ] Consider process logic, ie, what is different between time student is assigned to mentor and time relationship is affirmed
- [ ] What happened to green "Assign to" after selecting new mentor?

#### Mentors
- [x] Degree shows as "Unknown" in main table if none selected
- [ ] Wire up *release* links on Student tab

#### Users
- [x] Add role for student workers that only gives access to Mentors page

# Later

#### Request a Mentor
- [ ] After clearing all locations that **eduran** is linked to, the med school shows on the mentor list with the icon but no text.
- [ ] Do show mentors with no openings, but indicate as much with a "limit reached" or "no openings" label
- [x] Any user with qualifying role can access page, but only Students can submit a request.
- [ ] Error alert not shown when submit fails
- [ ] Polish the feedback & display after submit success

#### Requests
- [ ] Illuminate items in mentor list that match user criteria

#### Mentors
- [ ] APR button doesn't recalculate width after pull
- [ ] After manual training location selection, make sure there is an extra blank location provided
- [ ] Show student dates in Status cell of student table in modal
- [ ] Need to account for non-current students (and no students) on Student tab
- [ ] Student tab data get lost after APR button click
- [ ] Main page search should search specialty

#### Locations
- [ ] Spruce up Mentors section of modal
- [ ] When adding, School is defaulted to "Unknown"

# Maybe

#### Mentors
- [ ] Improve APR matching, i.e., consider city/state/country/etc
- [ ] If APR is clicked while editing, highlight fields that changed

#### Scoring
- [x] Does scoring algorithm take requested mentor into account?  Maybe it shouldn't, but should somehow illuminate requested mentor in list?
- [ ] Give points to MedSchool if it matches one of the training locations, and vice versa
- [ ] Consider City/State/Country
- [ ] Give point(s) for school match even if college doesn't match

# Future
- [ ] *Mentor locations* page needed so roles can be assigned to mentor locations
- [ ] Add Request History data to Requests modal

# Questions
- [ ] Textual changes: home page, etc
- [ ] What are rules for Cancel Request, Cancel Assignment?  Is there a point at which these aren't allowed?

**Comment by pj00** [comment]
closed to #5
