### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by pj00** [CCOMIT/CareerSpecialtyMentorRequest#5]
# Now

#### General
- [x] Deletes **double check Request**

#### Requests
- [x] Main page needs filter buttons
- [x] Wire up modal buttons
- [x] Degree shows as "Unknown" on main page
- [x] Flesh out the text in confirmation dialog for Assign to Mentor
- [x] Show notification recipients in confirmation dialogs

#### Mentors
- [x] Filter modal based on AppUser specialty
- [x] Try saving a hawkid that already exists and weird stuff happens
- [x] ~~Can we get Gender/Race/Ethnicity from HR?~~
- [x] How can we get emeritus faculty?

# Sooner

#### General
- [ ] Error page needed, e.g., if you log in as someone with no roles you get blank page w/ no explanation
- [ ] Notifications/Dispatch
  * Include notification to (matchmaker?) when all slots are filled
- [ ] Impersonation
- [ ] Is each DataTable search searching everything it needs to?

### Requests
- [x] Add Cancel and Release buttons, both with confirmation dialogs
- [x] Refine the logic for when the new modal buttons are used/enabled/etc
- [ ] Consider process logic, ie, what is different between time student is assigned to mentor and time relationship is affirmed
- [x] What happened to green "Assign to" after assigning/selecting new mentor?

#### Mentors
- [ ] Error deleting (on Test, per Choi;  ****norepro on dev****)

#### Users

# Later

#### Security
- [ ] AppUser.Active == false has no effect

#### Request a Mentor
- [ ] After clearing all locations that **eduran** is linked to, the med school shows on the mentor list with the icon but no text.
- [ ] Do show mentors with no openings, but indicate as much with a "limit reached" or "no openings" label
- [ ] Error alert not shown when submit fails
- [ ] Polish the feedback & display after submit success

#### Requests
- [ ] Illuminate items in mentor list that match user criteria
- [ ] Add Request History tab to Requests modal

#### Mentors
- [ ] Ability to designate SSFA/CSM
- [x] APR button doesn't recalculate width after pull
- [ ] After manual training location selection, make sure there is an extra blank location provided
- [ ] Show student dates in Status cell of student table in modal
- [x] Need to account for non-current students (and no students) on Student tab
- [ ] Student tab data get lost after APR button click
- [x] Main page search should search specialty
- [ ] If you have a long med school or tx location in modal, you can't see the "role at location".  If you hover, you get unformatted html for the hover text.
- [ ] Wire up *release* links on Student tab

#### Locations
- [ ] Spruce up Mentors section of modal
- [ ] When adding, School is defaulted to "Unknown"

#### Student Survey
- [ ] "Have you been contacted by mentor" yes/no

# Maybe

#### Mentors
- [ ] Improve APR matching, i.e., consider city/state/country/etc
- [ ] If APR is clicked while editing, highlight fields that changed

#### Scoring
- [ ] Give points to MedSchool if it matches one of the training locations, and vice versa
- [ ] Consider City/State/Country
- [ ] Give point(s) for school match even if college doesn't match

# Future
- [ ] *Mentor locations* page needed so roles can be assigned to mentor locations

# Questions
- [ ] Textual changes: home page, etc
- [ ] What are rules for Cancel Request, Cancel Assignment?  Is there a point at which these aren't allowed?
- [ ] Students are allowed to make multiple requests, but do we want to disallow if they are assigned?

**Comment by pj00** [comment]
closed to #6
