### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by pj00** [CCOMIT/CareerSpecialtyMentorRequest#6]
# Now

#### General
- [x] Error page needed, e.g., if you log in as someone with no roles you get blank page w/ no explanation
- [ ] Notifications/Dispatch
  - [x] Mentor requested => POCs, deciders (when appl.)
  - [x] Request canceled => POCs, student
  - [x] Mentor assigned => POCs, student, mentor
  - [x] Mentorship concluded => POCs, student, mentor
  - [x] Mentorship canceled => POCs, student, mentor
  - [ ] Two-week confirmation => student
  - [ ] Two-week confirmation response => POCs
  - [ ] Include notification to (matchmaker?) when all slots are filled
- [x] Is each DataTable search searching everything it needs to?

# Sooner

#### Request a Mentor
- [ ] After clearing all locations that **eduran** is linked to, the med school shows on the mentor list with the icon but no text.
- [ ] Do show mentors with no openings, but indicate as much with a "limit reached" or "no openings" label
- [ ] Error alert not shown when submit fails
- [ ] Polish the feedback & display after submit success

# Later

#### General
- [ ] Impersonation
- [ ] Persist filter button selections

#### Security
- [ ] AppUser.Active == false has no effect

#### Requests
- [ ] Illuminate items in mentor list that match user criteria
- [ ] Add Request History tab to Requests modal

#### Mentors
- [ ] Ability to designate SSFA/CSM
- [ ] After manual training location selection, make sure there is an extra blank location provided
- [ ] Show student dates in Status cell of student table in modal
- [ ] Student tab data get lost after APR button click
- [ ] If you have a long med school or tx location in modal, you can't see the "role at location".  If you hover, you get unformatted html for the hover text.
- [ ] Wire up *release* links on Student tab

#### Locations
- [ ] Spruce up Mentors section of modal
- [ ] When adding, School is defaulted to "Unknown"

#### Student Survey
- [ ] "Have you been contacted by mentor" yes/no

# Maybe

#### General
- [ ] DataTables search input needs delay; it updates after every keystroke
- [ ] DataTables search input needs clear button
- [ ] If APR is clicked while editing, highlight fields that changed

#### Mentors
- [ ] Improve APR matching, i.e., consider city/state/country/etc
- [ ] If APR is clicked while editing, highlight fields that changed

#### Scoring
- [ ] Give points to MedSchool if it matches one of the training locations, and vice versa
- [ ] Consider City/State/Country
- [ ] Give point(s) for school match even if college doesn't match

# Future
- [ ] *Mentor locations* page needed so roles can be assigned to mentor locations

# Questions
- [ ] Textual changes: home page, etc **waiting**
- [x] ~~What are rules for Cancel Request, Cancel Assignment?  Is there a point at which these aren't allowed?~~ **ok as is**
- [x] Students are allowed to make multiple requests, but do we want to disallow if they are assigned? **answered**
- [x] ~~Consider process logic, ie, what is different between time student is assigned to mentor and time relationship is affirmed~~ **ok as is**
- [x] Error deleting Mentor (on Test, per Choi;  ****norepro on dev or test****) **keeping an eye on it**
- [x] Who gets notification when all slots are filled? **answered**
- [ ] What account will we use as sender address for Dispatch? **waiting**

**Comment by pj00** [comment]
closed to #7 and #8
