### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by pj00** [CCOMIT/CareerSpecialtyMentorRequest#8]
# Now

- [x] What account will we use as sender address for Dispatch? **get him email request link**

#### General
- [x] Notifications/Dispatch
  - [x] Migrate to CCOM.OSAC.CSMR
  - [x] Choi should receive all notifications
  - [x] Two-week confirmation => student
  - [x] Dr Choi, matchmakers and managers (and admins, I would say) should be the ones to receive notifications when all mentor openings are filled

#### Request a Mentor
- [x] Dropdown lists should contain all options, but disable any that don't have a matching mentor

# Sooner

#### Request a Mentor
- [ ] After clearing all locations that **eduran** is linked to, the med school shows on the mentor list with the icon but no text.
- [ ] Do show mentors with no openings, but indicate as much with a "limit reached" or "no openings" label
- [ ] Error alert not shown when submit fails
- [ ] Polish the feedback & display after submit success
- [ ] No feedback if you click Submit and session has timed out

# Later

#### General
- [ ] Impersonation
- [ ] Persist filter button selections

#### Security
- [ ] AppUser.Active == false has no effect

#### Requests
- [ ] Illuminate items in mentor list that match user criteria
- [ ] Add Request History tab to Requests modal

#### Mentors
- [ ] Ability to designate SSFA/CSM
- [ ] After making a manual training location selection, make sure there is an extra blank location provided
- [ ] Show student dates in Status cell of student table in modal
- [ ] Student tab data get lost after APR button click
- [ ] If you have a long med school or tx location in modal, you can't see the "role at location".  If you hover, you get unformatted html for the hover text.
- [ ] Wire up *release* links on Student tab

#### Locations
- [ ] Spruce up Mentors section of modal
- [ ] When adding, School is defaulted to "Unknown"

#### Student Survey
- [ ] Notifications/Dispatch
  - [ ] Figure out confirmation notification automation (StatusCake?)
  - [ ] Two-week confirmation response => POCs
- [ ] "Have you been contacted by mentor" **waiting on specs (options)**

# Maybe

#### General
- [ ] DataTables search input needs delay; it updates after every keystroke
- [ ] DataTables search input needs clear button
- [ ] If APR is clicked while editing, highlight fields that changed

#### Requests
- [ ] Illuminate items in mentor list that match user criteria

#### Mentors
- [ ] Improve APR matching, i.e., consider city/state/country/etc
- [ ] If APR is clicked while editing, highlight fields that changed

#### Scoring
- [ ] Give points to MedSchool if it matches one of the training locations, and vice versa
- [ ] Consider City/State/Country
- [ ] Give point(s) for school match even if college doesn't match

# Waiting on
- [ ] Textual changes: home page, etc
- [ ] Dr Choi will provide a mock up of how the home page should look
- [ ] Sender email account
- [ ] Dr Choi will ponder modifications to race and ethnicity, and consider the possibility of adding a Countries dropdown
- [ ] It was decided the surveys will have more options than just yes/no. Dr Choi will come up with the options and associated text.

**Comment by pj00** [comment]
closed to #9 #10 #11 #12 #13 #14
